### ISSUE TITLE
prefilterTechList removes too many technologies

### ISSUE THREAD

**Issue by scheidan** [santiago-sanitation-systems/Santiago.jl#18]
In some cases `prefilterTechList` removes too many technologies so not all possible systems can be build.

 This was the cause #17. 

Currently `prefilterTechList` is not used anymore to guarantee the same results as with SanitationSystemMassFlow.

**Comment by spuhlerd** [comment]
is this still open?

**Comment by scheidan** [comment]
Yes. But we do not use it in the moment, so it's only about performance.

**Comment by scheidan** [comment]
Rewrite prefilter completely:

- `build_systems` takes an optional argument `product_hierarchy::Dict{Product}{Array{product}}`. A `product_hierarchy` Dict describes for each source product, which products may occur later in the system. 
- Probably it will be simpler to define the opposite, i.e. list for each source product the products that _cannot_ occur later in the system.
