### ISSUE TITLE
Features for future users

### ISSUE THREAD

**Issue by spuhlerd** [santiago-sanitation-systems/Santiago.jl#19]
Print:
- [x]  import techs (how many sources, techs, tech variations, etc. ... also looped techs)
- [x]  allSys: how many systems, how many templates, etc...

Other features:
- [ ] Export properties file: add feature "export all"
- [ ] Print all selected and all to PDF

**Comment by scheidan** [comment]
`massflow_stats` contains 424 numbers per system. It is hard to imagine a scenario where you want need them all

**Comment by scheidan** [comment]
The remaining stuff should go to the wiki, see #22
