### ISSUE TITLE
rewrite `template!`

### ISSUE THREAD

**Issue by scheidan** [santiago-sanitation-systems/Santiago.jl#20]
make sure that we only have to define a single table with the conditions

**Comment by spuhlerd** [comment]
anyway, if we extend the tech library (e.g. to emergency specific techs) we will need to work on this/ update improve etc.

**Comment by scheidan** [comment]
The templates are depend on the tech library (e.g. naming conventions). 
Therefore in the mid-term we should think about if the `template!` should be part of Santiago at all. Unfortunately writing a template function is a bit too complex for many end user.

**Comment by scheidan** [comment]
closed in favor of #74
