### ISSUE TITLE
User documentation for wiki

### ISSUE THREAD

**Issue by scheidan** [santiago-sanitation-systems/Santiago.jl#22]
A list of topics that should go into the wiki

- Why and how to work with Julia environments (`import Pkg; Pkg.activate("."); Pkg.instantiate()`)?
- How to print (selected) systems to pdf on different operating systems? What needs to be installed first?
- How to write a csv with the important massflow statistics?
- What do the performance functions (`Range`, `Trapez`, ...) mean and how are the parameter defined?
- Ho to use multi-threading, in particular for mass-flow calculations.

**Comment by Julianfritzsche2** [comment]
User documentation is done so far, some topics might still be missing or insufficient. Multi threading was not yet documented.
