### ISSUE TITLE
`build_systems` only works without `additional sources`

### ISSUE THREAD

**Issue by Julianfritzsche2** [santiago-sanitation-systems/Santiago.jl#27]
```Julia
julia >println("Sources found: $(sources)")
Sources found: Santiago.AbstractTech[u1.cistern.flush: (Source) -> (blackwater), u2.pour.flush: (Source) -> (blackwater), u3.dry.toilet: (Source) -> (excreta), u4.uddt: (Source) -> (urine, faeces)]

julia> println("Non-toilet sources found: $(additional_sources)")
Non-toilet sources found: Santiago.AbstractTech[]

julia> println("Number of techs found: $(length(techs))")
Number of techs found: 605

julia > allSys = build_systems(sources, additional_sources, techs);
ERROR: MethodError: no method matching build_systems(::Array{Santiago.AbstractTech,1}, ::Array{Santiago.AbstractTech,1}, ::Array{Santiago.AbstractTech,1})
```

`allSys = build_systems(sources, techs);` works fine, perhaps because `additional_sources` is zero or a strange array (see code above)? 

Additional question:
Where are `additional_sources` defined?

**Comment by scheidan** [comment]
The `additional_sources` are read from the techfile (but not all techfiles have additional sources):

```Julia
sources, additional_sources, techs = import_technologies(input_tech_file, input_case_file)
```

By default `additional_sources` are ignored: 
```build_systems(sources, techs)```

 You can pass them as keyword argument like this:
```build_systems(sources, techs, additional_sources=additional_sources)```

**Comment by Julianfritzsche2** [comment]
Just to make sure, the best practice runfile should contain the following code:
 `build_systems(sources, techs, additional_sources=additional_sources)`?

Or should there also a command without `additional_sources`?

**Comment by scheidan** [comment]
The version with `additional_sources` will always work, so maybe this is the best one for the wiki.
