### ISSUE TITLE
Explore and export tas components and other tech properties

### ISSUE THREAD

**Issue by Julianfritzsche2** [santiago-sanitation-systems/Santiago.jl#28]
Issue #26 also refers to the functionality to interface R scripts

(Could not find the corresponding code in the older Runfile)

**Comment by scheidan** [comment]
Needs first a way to flatten the nested Dict to a DataFrame

**Comment by spuhlerd** [comment]
to be done by julian, please prioritse to get the Rscripts ready for the students...

**Comment by spuhlerd** [comment]
appropriateness () recalculates the TAS and TAS components.
What we need is to explore them and export these together with other tech properties to a csv for plotting.

**Comment by spuhlerd** [comment]
make json and read in as list to R -> convert to dataframe

**Comment by spuhlerd** [comment]
read me and best practice file are now updated in order to store once calculated tas. has to be integrated in wiki
