### ISSUE TITLE
Additional filter in `system_select`

### ISSUE THREAD

**Issue by scheidan** [santiago-sanitation-systems/Santiago.jl#32]
Allow to filter system selection in `system_select`:

- [x] include/exclude templates
- [x] include/exclude technologies

**Comment by spuhlerd** [comment]
selectedSys = select_systems_SAS_template(allSys, nsystems, exclude_templates, exclude_techs)
selectSys = select_systems_recovery(allSys, nsystems, substance)
SelectSys = select_systems_ID(allSys, IDs)

**Comment by scheidan** [comment]
@spuhlerd How should `select_systems_recovery(allSys, nsystems, substance)` behave exactly?

1. Take the `nsystems`with the highest _recovery ratio_ of `substance`?
2. Take the `nsystems`with the highest _recovered mass_ `substance`?

**Comment by scheidan** [comment]
This is implemented now, see the example in the readme.

Note, selection by ID was postponed, because currently there is no guarantee that the IDs remain constant. Probably we need to use a hash or something
