### ISSUE TITLE
Case-independent properties to compute new system properties

### ISSUE THREAD

**Issue by spuhlerd** [santiago-sanitation-systems/Santiago.jl#33]
Four additional attributes in each tech which are not used to calculate TAS but aggregated to system attributes.
- categorical performance function (pcat)
- three categories, that takes a value between 0 and 100% (e.g. 0, 50, or 100%)
- When value missing: ignore... if value missing for more than half of techs, say that NA
- Aggregation: mean + max + min for each property and each category over all technologies

Applicability.level: House, Neighborhood, City
Management.level: Home, Shared, Public
Technical.complexity.level: Low, Moderate, High
Cost.level: Low, Moderate, High
System.complexity: make different -> see other issue #39

**Comment by spuhlerd** [comment]
how easy/difficult is it to add additional ones (in the case always the same format of three levels of 0, 0.5, 1.0 is used)?

**Comment by scheidan** [comment]
We could change the input format so that a tech has not only has `attributes` but additionally `extended_attributes` (better name needed!). The `extended_attributes` would be defined in the same way as the `attributes` (`Range`, `Categorical`, `Trapez`, ...) and we could have as many of them as we want.

This seems to be the cleanest approach to me.

**Comment by spuhlerd** [comment]
new name "case independent properties"

**Comment by spuhlerd** [comment]
Technical.complexity.level: Low, Moderate, High is calculated and taken care of issue #39

**Comment by scheidan** [comment]
Currently on hold. 

It may be the better solution to store the case independent attributes in database of the UI; `Santiago` itself does not make any calculation with this data.

**Comment by spuhlerd** [comment]
implemented in SaniChoice frontend/backend as "pre-filter criteria" and "addtional evaluation criteria"
