### ISSUE TITLE
System configureation complexity

### ISSUE THREAD

**Issue by spuhlerd** [santiago-sanitation-systems/Santiago.jl#39]
Create system property for evaluating complexity
e.g. System.configuration.complexity = ntech + connectivity
-> find a good formula that allows cross comparison of many systems, optionally score between 0 and 1

Maybe consult with Lilian Manny how to weight different aspects of configuration complexity such as connections, ntechs

**Comment by scheidan** [comment]
`number of connections` could be a good number. -> store in system properties

**Comment by spuhlerd** [comment]
We will use the number of connections as a proxy for complexity.
To do so, we need to save "number of connections" explicitly in the system properties -> to do

**Comment by scheidan** [comment]
`nconnections` implemented by 610f615
