### ISSUE TITLE
how to make SAS components available?

### ISSUE THREAD

**Issue by spuhlerd** [santiago-sanitation-systems/Santiago.jl#42]
SAS dashboard in fornt-end?
Or add SAS components to properties of systems
SAS components:
1) tech scores
2) tech score attributes, tas components

**Comment by scheidan** [comment]
We already have this. Every `tech` has a field `appscore`, and every `system` has a set of `tech`s. So you could get all TAS for a `sys` by:
```Julia
all_TAS_of_sys = [t.appscore[1] for t in sys.techs]
```
These numbers are also in the `JSON` export.

The TAS components of all Techs are can be obtained by:
```Julia
tas, tas_components = appropriateness(tech_file, case_file);
```
So one would only have to filter the teh techs used by a given system.

**Comment by spuhlerd** [comment]
So does that mean, that we can from the SaniCHOICE 'dashboard' directly call the data as it is exported?

**Comment by scheidan** [comment]
Yes, that's what I would expect.

**Comment by spuhlerd** [comment]
I reopen this issue becaus I think appropriateness() is not doing what we want here

**Comment by spuhlerd** [comment]
appropriateness() calculates once but is automated in "import_technologies()
to read out tas and tas_components, simple assess these objects
