### ISSUE TITLE
How to deal with different attribute functions for the same criteria

### ISSUE THREAD

**Issue by spuhlerd** [santiago-sanitation-systems/Santiago.jl#46]
- In some cases the available data suits categorical functions, in some cases continous functions (e.g. water supply)
- in the library, we have now different types of functions that might be used for a given technology for different criteria
- so far, the user defined itself the casefiles and techfiles and made sure that he used the function of preference and that teh case and tech function fit to each other
- if we provide the tech data, we have to help him select the most suitable function
- an easy way around would be to use different attributes (names) for different functions for the same criteria: e.g. "waterrequirements_tribblecat" and "waterrequirements_hoursday"

**Comment by scheidan** [comment]
The last option would need no change on the `Santiago` side.
I only wonder, if this is not more confusing to have two attributes for the same thing... Also, for categories I still have to guess  a continuous number to know which category to chose.

**Comment by spuhlerd** [comment]
can we discuss this in a meeting next monday?

**Comment by spuhlerd** [comment]
I looked at this again.
1) we could reduce the type of functions to two only but still cover all possibilities:
- cat: here for each attribute we would need to predefine number and name of categories
- continuous (based on trapez): 4 values a,b,c,d, fortrapez -  triangle, b=c - continuous a=b, c=d. like this, the user could define visually with sliders his case
2) To allow both at the same time for a same attribute we have two options:
- in the tech library we have for each attribute both a cat and a continous function
- something that allows us to translate categorical functions into continous and vice-versa

And we discuss this soon?

**Comment by spuhlerd** [comment]
1) Different attributes for different context, e.g. urban, emergency: use different namings, e.g. water.supply and emergency.water supply
2) Different functions for same attributes: use naming, e.g. water.supply.cont, water.supply.cat
3) Different continues functions: reduce risk for ill definition -> only always and ever from now on, we use trapezoidal function. In case data is triangular use b=c, e.g. (f(a=2, b=10, c=10, d=20). In case data is range only us b=a, c=d, e.g. (f(a=5, b=5, c=20, d=20)
4) ladder functions: translate all to categorical because we do not really know, if from one category (e.g. 1="mason") to the other (e.g. 2="expert") and yet a third (e.g.="engineer") the distances are really all the same
