### ISSUE TITLE
store "selected" in sys properties

### ISSUE THREAD

**Issue by spuhlerd** [santiago-sanitation-systems/Santiago.jl#47]
this would be useful to have it in the csv file. 
If you are sure that it would be confusing for the json export, than you might help us how to add it to the df?

**Comment by scheidan** [comment]
I would do something like this (not tested) First, export the properties of all systems and of the selected systems (you may also different sets of selected systems)
```Julia
CSV.write("all_systems.csv", properties_dataframe(allSys))
CSV.write("selected_systems.csv", properties_dataframe(selectedSys))
```
and the in R:
```R
# ... import "all_systems.csv" and "selected_systems.csv"
all.systems$selected <- all.systems$ID %in% selected.systems$ID
```

**Comment by Julianfritzsche2** [comment]
Solved with `props$selected <- props$ID %in% selectedSystems$ID`, whereas `props` is data frame with all systems and `selectedSystems` is data frame with selected Systems
