### ISSUE TITLE
better documentation of select_systems() - requested by Dotwerkstatt

### ISSUE THREAD

**Issue by spuhlerd** [santiago-sanitation-systems/Santiago.jl#61]
Either in the readme or in the help provide a concise clear overview of all options for select_systems
- (exclude/inlcude is quite clear)
- which substances
- which other options (ranking, ntechs, etc...)
- what combinations would work

**Comment by scheidan** [comment]
All substances names can be accessed via `Santiago.SUBSTANCE_NAMES`, i.e. `"phosphor",  "nitrogen", "water", "totalsolids"`.

Like most functions `select_system` has a quite extensive docstring. You can access it in Julia by typing `?select_system` to get the following info:

### The docstring of `select_system`:

```Julia
select_systems(systems::Array{System, N} where N, n_select::Int64; target, maximize, selection_type, techs_include, techs_exclude, templates_include, templates_exclude) -> Vector{System}
```

Select a subset of maximal `n_select` systems. The function aims to
 identify systems that have a good target value.

Most system properties can serve as target. The most commonly used one is the `sysappscore`.

## Arguments
- `n_select::Int` Number of systems to select (if possible)
- `target = "sysappscore"` value used ot rank systems. Can be a string
  with the name of a system property such as `"sysappscore"`,
  `"connectivity"`, or `"ntechs"`. For massflow statistics is needs to be a
`Pair` such as `("phosphsor" => "recovery_ratios")`
- `maximize::Bool = true` If `true` the system with the largest `target`
values are selected. If `false` the smallest.
- `selection_type = "diverse"` Must be either `"diverse"` or
 `"ranking"`. If `"ranking"`, the systems with the largest (or
 smallest) target values are returned. If `"diverse"`, the returned
 systems have a large (or small) target value but are also as diverse as
 possible. Diversity is mainly determined by the system templates.

The following optional arguments may be used to restrict the selection further:
- `techs_include`
- `techs_exclude`
- `templates_include`
- `templates_exclude`
For the templates only the first few characters must be provided.

Note, this function may add properties to the input systems! Any of
the following properties may be added if missing:

- `template`
- `sysappscore`
- `ntech`
- `connectivity`
