### ISSUE TITLE
technologies.json and tech_file

### ISSUE THREAD

**Issue by spuhlerd** [santiago-sanitation-systems/Santiago.jl#66]
In the webservices a global technologies.json file will be loaded once every XXXX days.
But when sending requests from the backend of SaniChoice, a preselection of technologies already happens before calculating appropriateness
thus
the webservice calculates the following:
```Julia
sources, additional_sources, techs  = import_technologies(tech_file_GLOBAL)
allSys = build_systems(sources, techs)
```
Then SaniChoice send following request:
```Julia
tas, tas_components = appropriateness(tech_file_SANICHOICE_SELECTION, case_file)
update_appropriateness!(sources, tas)
update_appropriateness!(additional_sources, tas)
update_appropriateness!(techs, tas)
```
-> how can we manage two different tech_files (_GLOBAL and _SANICHOICE_SELECTION) and even use the smaller selection to optimise `select_systems`?

**Comment by scheidan** [comment]
I don't see why we would have two different tech files. If you only want systems with certain techs, you do this with `select_system`:
```Julia
select_systems(allSys, 8, techs_include=SANICHOICE_TECH_SELECTION)
```
Computing the TAS and is very fast, so the overhead for doing it for every tech is minimal.

**Comment by spuhlerd** [comment]
You would have two different tech files in case you want to exclude some technologies right from the beginning, for instance if you are not in a humanitarian context you do not want the technologies specifically designed for humanitarian crisis or maybe your are only interested in very recent innovations or conventional technologies.... however, if i is not o much of an overhead, this can be dealt with in the frontend.

BUT: why do you need to send a tech_file then, wouldn't it be better to just send the case_file as the techfile is already loaded at the webservice....?

**Comment by scheidan** [comment]
The front-end does not need to send a techfile (this is local on the web-servise), just the case file.
