### ISSUE TITLE
Webservice only: avoid mutating techs and systems

### ISSUE THREAD

**Issue by scheidan** [santiago-sanitation-systems/Santiago.jl#78]
The webservice serves multiple users in parallel, so the mutations of `allSys` and `techs` leads to troubles (santiago-sanitation-systems/Santiago-webservice#12). Envisioned solution:

1. `sysappscore(s::System, tas; α = 0.5)`: match the techs with  `tas` for calculation.
2. `select_systems(allSys, ..., TAS)`: computes the SAS for all systems based on `TAS` but does not store it in the systems.
2.  `JSON3.write(s::System, SAS::Dict)`: construct a json file with updated SAS property.

**Comment by scheidan** [comment]
The current solution looks as follows:
```Julia

... build systems and compute massflows as usual...

# compute TAS (does not modify the techs)
tas, tas_components = appropriateness(input_tech_file, input_case_file)

# Select systems. You can use the usual arguments, but you need to pass `tas` additionally
selected_sys = Santiago.select_systems_web(allSys, 33, tas,
                                     target = "sysappscore",
                                     selection_type = "ranking")

# Scale massflows and export json
n_user = 10 # for massflow scaling
JSON3.write(selected_sys, tas, n_user)  # This does the mass flow scaling and updates the SAS
```

It is not very pretty that the `JSON3.write` with the extended arguments does the SAS calculations and the massflow scaling. However, this way we can completely avoid additional copying.

On the webservice `tas` has to be reconstructed from the json query. It must be of type `Dict{String}{Float64}`.

**Comment by spuhlerd** [comment]
![image](https://user-images.githubusercontent.com/34094350/134665758-77b15c64-4eb3-44d1-8d6f-136b8306b327.png)
I have updated the architecture according to recent changes (in red)
